name: Github Action Test
on: push
jobs:
  my-job:
    name: GitHubAction
    runs-on: ubuntu
    steps:
    - name: Clone GIT
      run: |
        git clone https://github.com/gogotomov/Playbook.git
    - name: List files in GIT
      run: |
        git show d6a3e51c9737286ed22c6cabe7c155fadc6848f8:Test1
